CREATE TABLE IF NOT EXISTS mainmenu(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
url TEXT NOT NULL,
article TEXT NOT NULL,
legendary_cars TEXT NOT NULL,
img_logo TEXT NOT NULL,
legendary TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS posts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
text TEXT NOT NULL,
post TEXT NOT NULL
);
